/*
 Navicat Premium Data Transfer

 Source Server         : online_books
 Source Server Type    : MySQL
 Source Server Version : 90100
 Source Host           : localhost:3306
 Source Schema         : online-books

 Target Server Type    : MySQL
 Target Server Version : 90100
 File Encoding         : 65001

 Date: 19/11/2024 15:02:44
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for book_chapter
-- ----------------------------
DROP TABLE IF EXISTS `book_chapter`;
CREATE TABLE `book_chapter` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `book_number` varchar(64) COLLATE utf8mb4_0900_bin NOT NULL COMMENT 'book number',
  `chapter_title` varchar(255) COLLATE utf8mb4_0900_bin DEFAULT NULL,
  `chapter_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,
  `chapter_audio` varchar(255) COLLATE utf8mb4_0900_bin DEFAULT NULL,
  `chapter_cover_image` varchar(255) COLLATE utf8mb4_0900_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

-- ----------------------------
-- Records of book_chapter
-- ----------------------------
BEGIN;
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (11, '141934450723393536', 'Chapters 01 to 02', 'Tom and his friend, Huckleberry Finn visited the graveyard one night and witnessed the murder of Dr. Robinson. In fear they ran away to an island but soon came back home when they learned that their parents thought they were dead. But what became of the murderer on the run?\r\n\r\nTom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_01-02_twain_64kb.mp3', 'https://www.loyalbooks.com/image/detail/49.jpg');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (12, '141934450723393536', 'Chapters 03 to 04', 'Tom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_03-04_twain_64kb.mp3', 'https://www.loyalbooks.com/image/detail/49.jpg');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (13, '141934450723393536', 'Chapters 05 to 06', 'Tom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_05-06_twain_64kb.mp3', 'https://www.loyalbooks.com/image/detail/49.jpg');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (14, '141934450723393536', 'Chapters 07 to 08', 'Tom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_07-08_twain_64kb.mp3', 'https://www.loyalbooks.com/image/detail/49.jpg');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (15, '141934450723393536', 'Chapters 09 to 10', 'Tom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_09-10_twain_64kb.mp3', 'https://www.loyalbooks.com/image/detail/49.jpg');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (16, '141934450723393536', 'Chapters 11 to 12', 'Tom Sawyer is a story told in such an engaging manner that you\'ll want to read it all in one sitting. The characters are vibrant and alive and the language simple, fun and engaging. If you have the stomach for such a story full of humor and horror, this book will not disappoint.', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_11-12_twain_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (17, '141934450723393536', 'Chapters 13 to 15', '', 'http://www.archive.org/download/tom_sawyer_librivox/TSawyer_13-14-15_twain_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (18, '141936486940545024', 'Up the Mountain to Alm-Uncle', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_01_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (19, '141936486940545024', 'At Home with Grandfather', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_02_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (20, '141936486940545024', 'Out With The Goats', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_03_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (21, '141936486940545024', 'The Visit to Grandmother', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_04_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (22, '141936486940545024', 'Two Visits and What Came of Them', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_05_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (23, '141936486940545024', 'A New Chapter About New Things', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_06_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (24, '141936486940545024', 'Fraulein Rottenmeier Spends an Uncomfortable Day', '', 'http://www.archive.org/download/heidi_solo_librivox/heidi_07_spyri_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (25, '141936486940545024', 'There is Great Commotion in the Large House', '', 'There is Great Commotion in the Large House', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (26, '141937780816220160', 'The Beginning of Things', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_01_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (27, '141937780816220160', 'Peter’s Coal-mine', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_02_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (28, '141937780816220160', 'The Old Gentleman', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_03_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (29, '141937780816220160', 'The Engine Burglar', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_04_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (30, '141937780816220160', 'Prisoners and Captives', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_05_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (31, '141937780816220160', 'Saviours of the Train', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_06_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (32, '141937780816220160', 'For Valour', '', 'http://www.archive.org/download/railway_children_librivox/railwaychildren_07_nesbit_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (33, '141939948239589376', 'How the Vikings of Old Sought And Found New Lands', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_01_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (34, '141939948239589376', 'The Sea of Darkness and the Great Faith of Columbus', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_02_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (35, '141939948239589376', 'How Columbus Fared Forth upon the Sea of Darkness and Came to Pleasant Lands Beyond', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_03_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (36, '141939948239589376', 'How Columbus Returned in Triumph', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_04_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (37, '141939948239589376', 'How America Was Named', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_05_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (38, '141939948239589376', 'How the Flag of England Was Planted on the Shores of the New World', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_06_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (39, '141939948239589376', 'How the Flag of France was Planted in Florida', '', 'http://www.archive.org/download/this_country_pt1_ks/this_country_07_marshall_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (40, '141941240819224576', 'Chapter 01', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_01_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (41, '141941240819224576', 'Chapter 02', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_02_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (42, '141941240819224576', 'Chapter 03', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_03_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (43, '141941240819224576', 'Chapter 04', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_04_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (44, '141941240819224576', 'Chapter 05', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_05_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (45, '141941240819224576', 'Chapter 06', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_06_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (46, '141941240819224576', 'Chapter 07', '', 'http://www.archive.org/download/great_expectations_mfs_0812_librivox/greatexpectations_07_dickens_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (47, '141942250753101824', 'Author’s Preface', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_00_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (48, '141942250753101824', 'The Three Presents of M. D’Artagnan the Elder', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_01_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (49, '141942250753101824', 'The Antechamber of M. de Treville', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_02_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (50, '141942250753101824', 'The Audience', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_03_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (51, '141942250753101824', 'The Shoulder of Athos, The Baldric of Porthos and the Handkerchief of Aramis', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_04_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (52, '141942250753101824', 'The King’s Musketeers and the Cardinal’s Guards', '', 'http://www.archive.org/download/three_musketeers_0712_librivox/three_musketeers_05_dumas_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (53, '141943116910432256', 'Mr. Bedford Meets Mr. Cavor in Lympne', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_01_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (54, '141943116910432256', 'The First Making of Cavorite', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_02_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (55, '141943116910432256', 'The Building of the Sphere', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_03_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (56, '141943116910432256', 'Inside the Sphere', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_04_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (57, '141943116910432256', 'The Journey to the Moon', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_05_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (58, '141943116910432256', 'The Landing on the Moon', '', 'http://www.archive.org/download/men_moon_mfs_librivox/first_men_in_moon_06_wells_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (59, '141943891841650688', 'Carthoris and Thuvia', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_01_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (60, '141943891841650688', ' Slavery', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_02_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (61, '141943891841650688', 'Treachery', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_03_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (62, '141943891841650688', 'A Green Man’s Captive', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_04_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (63, '141943891841650688', 'The Fair Race', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_05_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (64, '141943891841650688', 'The Jeddak of Lothar', '', 'http://www.archive.org/download/thuvia_0901_librivox/thuviamaidofmars_06_burroughs_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (65, '141944660963758080', 'Silver Blaze', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs01doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (66, '141944660963758080', 'The Yellow Face', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs02doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (67, '141944660963758080', 'The Stock-Broker’s Clerk', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs03doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (68, '141944660963758080', 'The Gloria Scott', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs04doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (69, '141944660963758080', 'The Musgrave Ritual', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs05doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (70, '141944660963758080', 'The Reigate Puzzle', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs06doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (71, '141944660963758080', 'The Crooked Man', '', 'http://www.archive.org/download/memoirs_holmes_0709_librivox/holmesmemoirs07doyle_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (72, '141945485085773824', 'Dedication', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_00_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (73, '141945485085773824', 'The Two Poets of Saffron Park', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_01_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (74, '141945485085773824', 'The Secret of Gabriel Syme', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_02_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (75, '141945485085773824', 'The Man Who Was Thursday', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_03_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (76, '141945485085773824', 'The Tale of a Detective', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_04_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (77, '141945485085773824', 'The Feast of Fear', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_05_chesterton_64kb.mp3', '');
INSERT INTO `book_chapter` (`id`, `book_number`, `chapter_title`, `chapter_content`, `chapter_audio`, `chapter_cover_image`) VALUES (78, '141945485085773824', 'The Exposure', '', 'http://www.archive.org/download/man_thursday_zach_librivox/man_who_was_thursday_06_chesterton_64kb.mp3', '');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
